name: mapbox_maps_flutter_platform_interface
description: "A common platform interface for the Mapbox Maps Flutter SDK, defining shared interfaces and data types."
version: 3.0.0-alpha.1
homepage: https://github.com/mapbox/mapbox-maps-flutter

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  turf: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
