// Autogenerated from Pigeon (v22.4.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

part of mapbox_maps_flutter;

enum _FollowPuckViewportStateBearing {
  constant,
  heading,
  course,
}

enum _ViewportStateType {
  idle,
  overview,
  followPuck,
  styleDefault,
  camera,
}

class _DefaultViewportTransitionOptions {
  _DefaultViewportTransitionOptions({
    required this.maxDurationMs,
  });

  int maxDurationMs;

  Object encode() {
    return <Object?>[
      maxDurationMs,
    ];
  }

  static _DefaultViewportTransitionOptions decode(Object result) {
    result as List<Object?>;
    return _DefaultViewportTransitionOptions(
      maxDurationMs: result[0]! as int,
    );
  }
}

class _OverviewViewportStateOptions {
  _OverviewViewportStateOptions({
    required this.geometry,
    required this.geometryPadding,
    this.bearing,
    this.pitch,
    this.padding,
    this.maxZoom,
    this.offset,
    required this.animationDurationMs,
  });

  String geometry;

  MbxEdgeInsets geometryPadding;

  double? bearing;

  double? pitch;

  MbxEdgeInsets? padding;

  double? maxZoom;

  ScreenCoordinate? offset;

  int animationDurationMs;

  Object encode() {
    return <Object?>[
      geometry,
      geometryPadding,
      bearing,
      pitch,
      padding,
      maxZoom,
      offset,
      animationDurationMs,
    ];
  }

  static _OverviewViewportStateOptions decode(Object result) {
    result as List<Object?>;
    return _OverviewViewportStateOptions(
      geometry: result[0]! as String,
      geometryPadding: result[1]! as MbxEdgeInsets,
      bearing: result[2] as double?,
      pitch: result[3] as double?,
      padding: result[4] as MbxEdgeInsets?,
      maxZoom: result[5] as double?,
      offset: result[6] as ScreenCoordinate?,
      animationDurationMs: result[7]! as int,
    );
  }
}

class _FollowPuckViewportStateOptions {
  _FollowPuckViewportStateOptions({
    this.padding,
    this.zoom,
    this.bearingValue,
    this.bearing,
    this.pitch,
  });

  MbxEdgeInsets? padding;

  double? zoom;

  double? bearingValue;

  _FollowPuckViewportStateBearing? bearing;

  double? pitch;

  Object encode() {
    return <Object?>[
      padding,
      zoom,
      bearingValue,
      bearing,
      pitch,
    ];
  }

  static _FollowPuckViewportStateOptions decode(Object result) {
    result as List<Object?>;
    return _FollowPuckViewportStateOptions(
      padding: result[0] as MbxEdgeInsets?,
      zoom: result[1] as double?,
      bearingValue: result[2] as double?,
      bearing: result[3] as _FollowPuckViewportStateBearing?,
      pitch: result[4] as double?,
    );
  }
}

class _ViewportStateStorage {
  _ViewportStateStorage({
    required this.type,
    this.options,
  });

  _ViewportStateType type;

  Object? options;

  Object encode() {
    return <Object?>[
      type,
      options,
    ];
  }

  static _ViewportStateStorage decode(Object result) {
    result as List<Object?>;
    return _ViewportStateStorage(
      type: result[0]! as _ViewportStateType,
      options: result[1],
    );
  }
}

/// Configuration options for [ViewportManager].
class ViewportOptions {
  ViewportOptions({
    required this.transitionsToIdleUponUserInteraction,
  });

  /// Indicates whether the [ViewportManager] should idle when the user interacts with the map using gestures.
  ///
  /// Set this property to [false] to enable building a custom [ViewportState] that
  /// can work simultaneously with certain types of gestures.
  ///
  /// Defaults to [true].
  bool transitionsToIdleUponUserInteraction;

  Object encode() {
    return <Object?>[
      transitionsToIdleUponUserInteraction,
    ];
  }

  static ViewportOptions decode(Object result) {
    result as List<Object?>;
    return ViewportOptions(
      transitionsToIdleUponUserInteraction: result[0]! as bool,
    );
  }
}

class ViewportInternal_PigeonCodec extends StandardMessageCodec {
  const ViewportInternal_PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is _FollowPuckViewportStateBearing) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is _ViewportStateType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is MbxEdgeInsets) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is ScreenCoordinate) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is _DefaultViewportTransitionOptions) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is _OverviewViewportStateOptions) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is _FollowPuckViewportStateOptions) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is _ViewportStateStorage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is ViewportOptions) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null
            ? null
            : _FollowPuckViewportStateBearing.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : _ViewportStateType.values[value];
      case 131:
        return MbxEdgeInsets.decode(readValue(buffer)!);
      case 132:
        return ScreenCoordinate.decode(readValue(buffer)!);
      case 133:
        return _DefaultViewportTransitionOptions.decode(readValue(buffer)!);
      case 134:
        return _OverviewViewportStateOptions.decode(readValue(buffer)!);
      case 135:
        return _FollowPuckViewportStateOptions.decode(readValue(buffer)!);
      case 136:
        return _ViewportStateStorage.decode(readValue(buffer)!);
      case 137:
        return ViewportOptions.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class _ViewportManagerMessenger {
  /// Constructor for [_ViewportManagerMessenger].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  _ViewportManagerMessenger(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec =
      ViewportInternal_PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Get configuration options for adjusting the behavior of [ViewportManager].
  Future<ViewportOptions> getOptions() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter._ViewportManagerMessenger.getOptions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ViewportOptions?)!;
    }
  }

  /// Set configuration options for adjusting the behavior of [ViewportManager].
  Future<void> setOptions(ViewportOptions options) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter._ViewportManagerMessenger.setOptions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> transition(
      _ViewportStateStorage stateStorage, int? transitionIdentifier) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter._ViewportManagerMessenger.transition$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[stateStorage, transitionIdentifier]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}
