name: mapbox_maps_flutter
description: "Mapbox Maps for Flutter. Provides interactive, customizable vector maps for Android, iOS, and Web."
version: 3.0.0-alpha.1
homepage: https://github.com/mapbox/mapbox-maps-flutter

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  turf: ^0.0.10
  meta: ^1.17.0
  flutter:
    sdk: flutter
  mapbox_maps_flutter_platform_interface: ^3.0.0-alpha.1
  mapbox_maps_flutter_mobile: ^3.0.0-alpha.1
  mapbox_maps_flutter_web: ^3.0.0-alpha.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: mapbox_maps_flutter_mobile
      ios:
        default_package: mapbox_maps_flutter_mobile
      web:
        default_package: mapbox_maps_flutter_web
