# This file configures Dart code analyzer to check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs. The analyzer can also be invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps and packages.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    library_private_types_in_public_api: error

# Additional information can be found at https://dart.dev/guides/language/analysis-options
