name: mapbox_maps_flutter_web
description: Web implementation of the Mapbox Maps Flutter plugin.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  mapbox_maps_flutter_platform_interface: ^0.0.1 # Change to fixed version when the platform interface is published.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      implements: mapbox_maps_flutter_platform_interface
      web:
        pluginClass: MapboxMapsFlutterWeb
        fileName: src/mapbox_maps_flutter_web.dart
