name: mapbox_maps_flutter_web
description: Web implementation of the Mapbox Maps Flutter plugin.
version: 9.9.9-alpha.99
homepage: https://github.com/mapbox/mapbox-maps-flutter

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  meta: ^1.17.0
  turf: ^0.0.10
  mapbox_maps_flutter_platform_interface: ^9.9.9-alpha.99

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: mapbox_maps_flutter
    platforms:
      web:
        pluginClass: MapboxMapsFlutterWeb
        fileName: src/mapbox_maps_flutter_web.dart
