name: mapbox_maps_flutter_web_example
description: Integration tests for the Mapbox Maps Flutter web plugin.
publish_to: 'none'

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter_web:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  web: ^1.0.0
  turf: ^0.0.10

flutter:
  uses-material-design: true
