// Autogenerated from Pigeon (v25.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

// ignore_for_file: experimental_member_use
part of mapbox_maps_flutter_mobile;

class GestureListeners_PigeonCodec extends StandardMessageCodec {
  const GestureListeners_PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is IconAnchor) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is IconTextFit) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is TextAnchor) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is TextJustify) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is TextTransform) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is LineJoin) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is GestureState) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is Point) {
      buffer.putUint8(136);
      writeValue(buffer, value.toJson());
    } else if (value is Polygon) {
      buffer.putUint8(137);
      writeValue(buffer, value.toJson());
    } else if (value is LineString) {
      buffer.putUint8(138);
      writeValue(buffer, value.toJson());
    } else if (value is ScreenCoordinate) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is MapContentGestureContext) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is PointAnnotation) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is CircleAnnotation) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is PolygonAnnotation) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is PolylineAnnotation) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is PointAnnotationInteractionContext) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is CircleAnnotationInteractionContext) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is PolygonAnnotationInteractionContext) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is PolylineAnnotationInteractionContext) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : IconAnchor.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : IconTextFit.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TextAnchor.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TextJustify.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TextTransform.values[value];
      case 134:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : LineJoin.values[value];
      case 135:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GestureState.values[value];
      case 136:
        return Point.fromJson(
          (readValue(buffer)! as Map).cast<String, dynamic>(),
        );
      case 137:
        return Polygon.fromJson(
          (readValue(buffer)! as Map).cast<String, dynamic>(),
        );
      case 138:
        return LineString.fromJson(
          (readValue(buffer)! as Map).cast<String, dynamic>(),
        );
      case 139:
        return ScreenCoordinate.decode(readValue(buffer)!);
      case 140:
        return MapContentGestureContext.decode(readValue(buffer)!);
      case 141:
        return PointAnnotation.decode(readValue(buffer)!);
      case 142:
        return CircleAnnotation.decode(readValue(buffer)!);
      case 143:
        return PolygonAnnotation.decode(readValue(buffer)!);
      case 144:
        return PolylineAnnotation.decode(readValue(buffer)!);
      case 145:
        return PointAnnotationInteractionContext.decode(readValue(buffer)!);
      case 146:
        return CircleAnnotationInteractionContext.decode(readValue(buffer)!);
      case 147:
        return PolygonAnnotationInteractionContext.decode(readValue(buffer)!);
      case 148:
        return PolylineAnnotationInteractionContext.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  GestureListeners_PigeonCodec(),
);

abstract class GestureListener {
  static const MessageCodec<Object?> pigeonChannelCodec =
      GestureListeners_PigeonCodec();

  void onTap(MapContentGestureContext context);

  void onLongTap(MapContentGestureContext context);

  void onScroll(MapContentGestureContext context);

  void onZoom(MapContentGestureContext context);

  static void setUp(
    GestureListener? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onTap was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final MapContentGestureContext? arg_context =
              (args[0] as MapContentGestureContext?);
          assert(
            arg_context != null,
            'Argument for dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onTap was null, expected non-null MapContentGestureContext.',
          );
          try {
            api.onTap(arg_context!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onLongTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onLongTap was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final MapContentGestureContext? arg_context =
              (args[0] as MapContentGestureContext?);
          assert(
            arg_context != null,
            'Argument for dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onLongTap was null, expected non-null MapContentGestureContext.',
          );
          try {
            api.onLongTap(arg_context!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onScroll$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onScroll was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final MapContentGestureContext? arg_context =
              (args[0] as MapContentGestureContext?);
          assert(
            arg_context != null,
            'Argument for dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onScroll was null, expected non-null MapContentGestureContext.',
          );
          try {
            api.onScroll(arg_context!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onZoom$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onZoom was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final MapContentGestureContext? arg_context =
              (args[0] as MapContentGestureContext?);
          assert(
            arg_context != null,
            'Argument for dev.flutter.pigeon.mapbox_maps_flutter.GestureListener.onZoom was null, expected non-null MapContentGestureContext.',
          );
          try {
            api.onZoom(arg_context!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

Stream<AnnotationInteractionContext> _annotationInteractionEvents({
  String instanceName = '',
}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel _annotationInteractionEventsChannel = EventChannel(
    'dev.flutter.pigeon.mapbox_maps_flutter.MapEventChannel._annotationInteractionEvents$instanceName',
    pigeonMethodCodec,
  );
  return _annotationInteractionEventsChannel.receiveBroadcastStream().map((
    dynamic event,
  ) {
    return event as AnnotationInteractionContext;
  });
}

Stream<MapContentGestureContext> _panEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel _panEventsChannel = EventChannel(
    'dev.flutter.pigeon.mapbox_maps_flutter.MapEventChannel._panEvents$instanceName',
    pigeonMethodCodec,
  );
  return _panEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as MapContentGestureContext;
  });
}

Stream<MapContentGestureContext> _zoomEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel _zoomEventsChannel = EventChannel(
    'dev.flutter.pigeon.mapbox_maps_flutter.MapEventChannel._zoomEvents$instanceName',
    pigeonMethodCodec,
  );
  return _zoomEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as MapContentGestureContext;
  });
}

Stream<MapContentGestureContext> _rotateEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel _rotateEventsChannel = EventChannel(
    'dev.flutter.pigeon.mapbox_maps_flutter.MapEventChannel._rotateEvents$instanceName',
    pigeonMethodCodec,
  );
  return _rotateEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as MapContentGestureContext;
  });
}

Stream<MapContentGestureContext> _pitchEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel _pitchEventsChannel = EventChannel(
    'dev.flutter.pigeon.mapbox_maps_flutter.MapEventChannel._pitchEvents$instanceName',
    pigeonMethodCodec,
  );
  return _pitchEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as MapContentGestureContext;
  });
}
