default_platform(:ios)

ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "1"
ENV["SPACESHIP_SKIP_2FA_UPGRADE"] = "1"

platform :ios do

  lane :build_examples_tests do
    setup_circle_ci
    sync_code_signing(type: "development")
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "mapbox_maps_flutter_mobile/example/ios/Runner.xcodeproj",
      team_id: "GJZR2MEM28", # Developer Portal Team ID,
      profile_name: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]["com.mapbox.maps.FlutterMapsExample"],
      targets: ["Runner"],
      code_sign_identity: "Apple Development: Created via API",
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "mapbox_maps_flutter_mobile/example/ios/Runner.xcodeproj",
      team_id: "GJZR2MEM28", # Developer Portal Team ID,
      profile_name: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]["com.mapbox.maps.FlutterRunnerTests"],
      targets: ["RunnerTests"],
      code_sign_identity: "Apple Development: Created via API",
    )
    # build tests archive in the `output_directory` to launch on firebase
    run_tests(
      workspace: 'mapbox_maps_flutter_mobile/example/ios/Runner.xcworkspace',
      scheme: 'Runner',                   # XCTest scheme
      xcconfig: "mapbox_maps_flutter_mobile/example/ios/Flutter/Release.xcconfig",
      derived_data_path: "mapbox_maps_flutter_mobile/example/build/output",
      configuration: "Release",
      xcargs: "SWIFT_TREAT_WARNINGS_AS_ERRORS=NO COMPILER_INDEX_STORE_ENABLE=NO",
      skip_detect_devices: true,          # Required
      build_for_testing: true,            # Required
      sdk: 'iphoneos',                    # Required
      should_zip_build_products: true,    # Must be true to set the correct format for Firebase Test Lab,
      result_bundle: true,
      output_directory: "mapbox_maps_flutter_mobile/example/build/output/",
      code_coverage: true
    )
  end

end
